"""Auto-sync: model changes

Revision ID: 18769a5d70eb
Revises: 73fe438fe608
Create Date: 2025-11-24 10:35:51.895970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18769a5d70eb'
down_revision: Union[str, None] = '73fe438fe608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
