"""add_unique_id_to_constituencies

Revision ID: 2b1da9ee1f5d
Revises: 
Create Date: 2025-11-13 13:42:04.451441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1da9ee1f5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add columns as nullable first (to handle existing data)
    op.add_column('candidates', sa.Column('original_constituency_id', sa.String(), nullable=True))
    op.add_column('constituencies', sa.Column('original_id', sa.String(), nullable=True))
    
    # Step 2: Populate original_id from existing id values in constituencies
    # This preserves the original ID before we potentially change the id column
    op.execute("""
        UPDATE constituencies 
        SET original_id = id 
        WHERE original_id IS NULL
    """)
    
    # Step 3: Populate original_constituency_id from existing constituency_id in candidates
    op.execute("""
        UPDATE candidates 
        SET original_constituency_id = constituency_id 
        WHERE original_constituency_id IS NULL
    """)
    
    # Step 4: Make original_id NOT NULL now that it's populated
    op.alter_column('constituencies', 'original_id', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('constituencies', 'original_id')
    op.drop_column('candidates', 'original_constituency_id')
    # ### end Alembic commands ###
