"""Auto-sync: model changes

Revision ID: 44a45c594b37
Revises: a1b2c3d4e5f6
Create Date: 2025-11-25 07:58:17.703313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44a45c594b37'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'topics_of_interest')
    op.drop_column('users', 'preferred_parties')
    op.drop_column('users', 'political_interest')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('political_interest', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_parties', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('topics_of_interest', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
