"""Auto-sync: model changes

Revision ID: 73fe438fe608
Revises: 20decf6f42ff
Create Date: 2025-11-24 10:35:08.705163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73fe438fe608'
down_revision: Union[str, None] = '20decf6f42ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect, text
    
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Add constituencies.type column (nullable first, then set default, then make NOT NULL)
    constituencies_columns = [c['name'] for c in inspector.get_columns('constituencies')]
    if 'type' not in constituencies_columns:
        # First add as nullable
        op.add_column('constituencies', sa.Column('type', sa.Enum('VS', 'LS', name='constituency_type'), nullable=True))
        # Set default value for existing rows (assuming LS for Lok Sabha)
        conn.execute(text("UPDATE constituencies SET type = 'LS' WHERE type IS NULL"))
        # Now make it NOT NULL
        op.alter_column('constituencies', 'type', nullable=False)
    
    # Add users columns if they don't exist
    users_columns = [c['name'] for c in inspector.get_columns('users')]
    
    if 'pincode' not in users_columns:
        op.add_column('users', sa.Column('pincode', sa.String(), nullable=True))
    if 'vs_constituency_id' not in users_columns:
        op.add_column('users', sa.Column('vs_constituency_id', sa.String(), nullable=True))
    if 'ls_constituency_id' not in users_columns:
        op.add_column('users', sa.Column('ls_constituency_id', sa.String(), nullable=True))
    if 'political_ideology' not in users_columns:
        op.add_column('users', sa.Column('political_ideology', sa.String(), nullable=True))
    
    # Add foreign keys if they don't exist
    foreign_keys = inspector.get_foreign_keys('users')
    fk_columns = [fk['constrained_columns'][0] for fk in foreign_keys]
    
    if 'ls_constituency_id' not in fk_columns:
        op.create_foreign_key('fk_users_ls_constituency', 'users', 'constituencies', ['ls_constituency_id'], ['id'])
    if 'vs_constituency_id' not in fk_columns:
        op.create_foreign_key('fk_users_vs_constituency', 'users', 'constituencies', ['vs_constituency_id'], ['id'])
    
    # Remove columns only if they exist (these were never actually in the model, just referenced in methods)
    if 'political_interest' in users_columns:
        op.drop_column('users', 'political_interest')
    if 'phone' in users_columns:
        op.drop_column('users', 'phone')
    if 'last_login' in users_columns:
        op.drop_column('users', 'last_login')
    if 'preferred_parties' in users_columns:
        op.drop_column('users', 'preferred_parties')
    if 'topics_of_interest' in users_columns:
        op.drop_column('users', 'topics_of_interest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('topics_of_interest', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_parties', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('political_interest', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'political_ideology')
    op.drop_column('users', 'ls_constituency_id')
    op.drop_column('users', 'vs_constituency_id')
    op.drop_column('users', 'pincode')
    op.drop_column('constituencies', 'type')
    # ### end Alembic commands ###
