"""Auto-sync: model changes

Revision ID: 93e1f7fdc7a0
Revises: 18769a5d70eb
Create Date: 2025-11-24 10:36:29.092071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e1f7fdc7a0'
down_revision: Union[str, None] = '18769a5d70eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
